import numpy as np
import torch
from loss_functions import AT_loss, generate_crackprior
from optim import WrapperNet, train


class CrackDetector:
    ''' CrackDetector takes pretrained models, loss parameters and optimization parameters as parameters. __call__ runs
    optimization wrt loss and returns
    Gz: the reconstructed background image
    v: the raw reconstruction of the crack (pre-thresholding) where v = 0 means crack, v = 1 means no crack (AT perspective)'''
    
    def __init__(self, vqgan, dcmodel, epsi, lam_preg, lam_creg, lam_crack, iters=500, lr_z=0.005, lr_v=0.1):
        
        # pretrained models 
        self.vqgan = vqgan
        self.dcmodel = dcmodel

        # hyperparameters
        self.epsi = epsi
        self.lam_preg = lam_preg
        self.lam_creg = lam_creg
        self.lam_crack = lam_crack
        
        # optimization parameters
        self.iters = iters
        self.lr_z = lr_z
        self.lr_v = lr_v


    def __call__(self, img):
        # for reference: the crack prediction generated by the deep crack prior
        if self.lam_crack != 0.0:
            if self.dcmodel is None:
                raise ValueError(
                    "dcmodel must be provided when lam_crack is nonzero."
                )
            p_dc = generate_crackprior(self.dcmodel, img).detach()
        else:
            p_dc = None

        custom_loss = AT_loss(
            self.vqgan,
            p_dc,
            self.epsi,
            self.lam_preg,
            self.lam_creg,
            self.lam_crack,
        )

        # our own prediction before post-processing
        model = WrapperNet(img, self.vqgan)
        model = train(
            model, 
            custom_loss, 
            iters = self.iters, 
            lr_z = self.lr_z, 
            lr_v = self.lr_v
        )
        
        s,z = model()

        # raw crack prediction v
        v = torch.sigmoid(s)

        # image prediction Gz
        z_q, _, _ = self.vqgan.quantize(z)
        Gz = self.vqgan.decode(z_q)  # generates an image from the latent variable z
        
        return Gz.detach(), v.detach(), p_dc
