import torch
import torch.nn.functional as F
from torch import nn

from math_utils import spatial_grad


def data_fidelity_loss(img, Gz, v):
    img = img * 2 - 1  # to match images generated by VQGAN, which are in [-1,1]
    return F.mse_loss(v * Gz, v * img)

def preg_loss(Gz, v):
    ux, uy = spatial_grad(Gz)
    grad_sq = (ux**2 + uy**2).sum(dim=1, keepdim=True)
    return (v * v * grad_sq).mean()

def creg_loss(v, epsi):
    # --- crack regularity ---
    # ∇v
    vx, vy = spatial_grad(v)
    # |∇v|^2
    v_grad = (vx**2 + vy**2).mean()
    # ε|∇v|^2 + (v-1)^2/(4ε)
    return epsi * v_grad + ((v - 1)**2 / (4 * epsi)).mean()

def deepcrack_loss(v, crackprior):
    crack_from_v = 1.0 - v
    return F.mse_loss(crack_from_v, crackprior)

def generate_crackprior(dcmodel, img):
    # --- DeepCrack prior ---
    with torch.no_grad():
        # 1️⃣ Normalize input (important for fine-tuned unfrozen model)
        mean = torch.tensor([0.485, 0.456, 0.406], device=img.device).view(1, 3, 1, 1)
        std = torch.tensor([0.229, 0.224, 0.225], device=img.device).view(1, 3, 1, 1)
        imgs_norm = (img - mean) / std

        # 2️⃣ Forward pass through DeepCrack
        dc_out = dcmodel(imgs_norm)

        # 3️⃣ Multi-scale output handling
        if isinstance(dc_out, (list, tuple)):
            # fuse1 (finest-scale side output), not the fused `output` head — matches
            # validate()'s output selection in finetune_DeepCrack.py, which is what this
            # checkpoint was actually selected and validated on.
            dc_logits = dc_out[-1]
        else:
            dc_logits = dc_out

        # 4️⃣ Apply Sigmoid to get probability map
        return torch.sigmoid(dc_logits)


class AT_loss(nn.Module):
    def __init__(self, vqgan, dcmodel, epsi, lam_preg, lam_creg, lam_crack):
        super().__init__()
        self.vqgan = vqgan
        self.crackprior = dcmodel
        self.epsi = epsi
        self.lam_preg = lam_preg
        self.lam_creg = lam_creg
        self.lam_crack = lam_crack

    def forward(self, img, model_output):
        s, z = model_output

        v = torch.sigmoid(s)
        # v is in (0,1), convert to rgb
        v_rgb = v.expand(-1, 3, -1, -1)

        z_q, _, _ = self.vqgan.quantize(z)
        Gz = self.vqgan.decode(z_q)  # generates an image from the latent variable z

        loss = (
            data_fidelity_loss(img, Gz, v_rgb)
            + self.lam_preg * preg_loss(Gz, v)
            + self.lam_creg * creg_loss(v, self.epsi)
        )

        if self.lam_crack != 0:
            loss = loss + self.lam_crack * deepcrack_loss(v, self.crackprior)

        return loss
